
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BuffEnum
    {
        None = 0,
        碎魂效果 = 1,
        壮魂效果 = 2,
        返回本我效果 = 3,
        /// <summary>
        /// 死期到0时，生命减少为0
        /// </summary>
        死期 = 4,
        /// <summary>
        /// 造成伤害无视敌方护甲
        /// </summary>
        黑无常 = 5,
        /// <summary>
        /// 造成伤害恢复等量生命
        /// </summary>
        白无常 = 6,
        /// <summary>
        /// 造成伤害后自己也掉血
        /// </summary>
        禁武令 = 7,
        /// <summary>
        /// 护甲清零，不能获得护甲
        /// </summary>
        卸甲令 = 8,
        /// <summary>
        /// 不能行动（但列表会往下走）
        /// </summary>
        监禁令 = 9,
    }

} 

