
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CardConfig : Luban.BeanBase
{
    public CardConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (CardEnum)_buf["id"].AsInt; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (CardTypeEnum)_buf["type"].AsInt; }
        { if(!_buf["intent"].IsNumber) { throw new SerializationException(); }  Intent = (IntentEnum)_buf["intent"].AsInt; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { var __json0 = _buf["value"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Value = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Value[__index0++] = __v0; }   }
        { if(!_buf["can_end_round"].IsBoolean) { throw new SerializationException(); }  CanEndRound = _buf["can_end_round"]; }
        { var __json0 = _buf["mask_to_card_effect"]; if(!__json0.IsArray) { throw new SerializationException(); } MaskToCardEffect = new System.Collections.Generic.Dictionary<MaskEnum, CardEnum>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { MaskEnum _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = (MaskEnum)__e0[0].AsInt; } CardEnum _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = (CardEnum)__e0[1].AsInt; }  MaskToCardEffect.Add(_k0, _v0); }   }
    }

    public static CardConfig DeserializeCardConfig(JSONNode _buf)
    {
        return new CardConfig(_buf);
    }

    public readonly CardEnum Id;
    public readonly CardTypeEnum Type;
    public readonly IntentEnum Intent;
    /// <summary>
    /// 卡牌名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    public readonly int[] Value;
    public readonly bool CanEndRound;
    public readonly System.Collections.Generic.Dictionary<MaskEnum, CardEnum> MaskToCardEffect;
   
    public const int __ID__ = -2113914222;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "intent:" + Intent + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "value:" + Luban.StringUtil.CollectionToString(Value) + ","
        + "canEndRound:" + CanEndRound + ","
        + "maskToCardEffect:" + Luban.StringUtil.CollectionToString(MaskToCardEffect) + ","
        + "}";
    }
}
}

