
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum CardTypeEnum
    {
        攻击 = 0,
        功能 = 1,
        请神 = 2,
        面具 = 3,
    }

} 

