
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class CardTable
{
    private readonly System.Collections.Generic.Dictionary<CardEnum, CardConfig> _dataMap;
    private readonly System.Collections.Generic.List<CardConfig> _dataList;
    
    public CardTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<CardEnum, CardConfig>(count);
        _dataList = new System.Collections.Generic.List<CardConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CardConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.CardConfig.DeserializeCardConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<CardEnum, CardConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<CardConfig> DataList => _dataList;

    public CardConfig GetOrDefault(CardEnum key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CardConfig Get(CardEnum key) => _dataMap[key];
    public CardConfig this[CardEnum key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

