
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CardConfig : Luban.BeanBase
{
    public CardConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (CardEnum)_buf["id"].AsInt; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["damage_value"].IsNumber) { throw new SerializationException(); }  DamageValue = _buf["damage_value"]; }
        { if(!_buf["shield_value"].IsNumber) { throw new SerializationException(); }  ShieldValue = _buf["shield_value"]; }
        { if(!_buf["health_value"].IsNumber) { throw new SerializationException(); }  HealthValue = _buf["health_value"]; }
        { if(!_buf["health_limit_value"].IsNumber) { throw new SerializationException(); }  HealthLimitValue = _buf["health_limit_value"]; }
        { if(!_buf["end_round_when_use"].IsBoolean) { throw new SerializationException(); }  EndRoundWhenUse = _buf["end_round_when_use"]; }
    }

    public static CardConfig DeserializeCardConfig(JSONNode _buf)
    {
        return new CardConfig(_buf);
    }

    public readonly CardEnum Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    public readonly int DamageValue;
    public readonly int ShieldValue;
    public readonly int HealthValue;
    public readonly int HealthLimitValue;
    /// <summary>
    /// 打出后结束回合?
    /// </summary>
    public readonly bool EndRoundWhenUse;
   
    public const int __ID__ = -2113914222;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "damageValue:" + DamageValue + ","
        + "shieldValue:" + ShieldValue + ","
        + "healthValue:" + HealthValue + ","
        + "healthLimitValue:" + HealthLimitValue + ","
        + "endRoundWhenUse:" + EndRoundWhenUse + ","
        + "}";
    }
}
}

