
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ElementEnum
    {
        /// <summary>
        /// 0
        /// </summary>
        None = 0,
        火 = 1,
        草 = 2,
        人造 = 3,
        风 = 4,
        毒 = 5,
        电 = 6,
        水 = 7,
    }

} 

