
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GameMapConfig : Luban.BeanBase
{
    public GameMapConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (GameMapEnum)_buf["id"].AsInt; }
        { if(!_buf["addressable_path"].IsString) { throw new SerializationException(); }  AddressablePath = _buf["addressable_path"]; }
    }

    public static GameMapConfig DeserializeGameMapConfig(JSONNode _buf)
    {
        return new GameMapConfig(_buf);
    }

    public readonly GameMapEnum Id;
    /// <summary>
    /// 加载路径
    /// </summary>
    public readonly string AddressablePath;
   
    public const int __ID__ = 1766192076;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "addressablePath:" + AddressablePath + ","
        + "}";
    }
}
}

