
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum GameLevelEnum
    {
        None = 0,
        第一关 = 1,
        第二关 = 2,
        第三关 = 3,
        第四关 = 4,
    }

} 

