
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class GameMapTable
{
    private readonly System.Collections.Generic.Dictionary<GameMapEnum, GameMapConfig> _dataMap;
    private readonly System.Collections.Generic.List<GameMapConfig> _dataList;
    
    public GameMapTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<GameMapEnum, GameMapConfig>(count);
        _dataList = new System.Collections.Generic.List<GameMapConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GameMapConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.GameMapConfig.DeserializeGameMapConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<GameMapEnum, GameMapConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<GameMapConfig> DataList => _dataList;

    public GameMapConfig GetOrDefault(GameMapEnum key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GameMapConfig Get(GameMapEnum key) => _dataMap[key];
    public GameMapConfig this[GameMapEnum key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

