
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum GameMapEnum
    {
        /// <summary>
        /// 开发测试地图
        /// </summary>
        Developer = -1,
        None = 0,
        /// <summary>
        /// 序章地图
        /// </summary>
        Started = 1,
        /// <summary>
        /// 第一章
        /// </summary>
        ForsakenCity = 2,
    }

} 

