
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum GhostEnum
    {
        水鬼 = 0,
        拔舌鬼 = 1,
        穷鬼 = 2,
        铜柱鬼 = 3,
        肉山鬼 = 4,
        阎王 = 5,
        黑白无常 = 6,
    }

} 

