
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GhostConfig : Luban.BeanBase
{
    public GhostConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (GhostEnum)_buf["id"].AsInt; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["prefab_path"].IsString) { throw new SerializationException(); }  PrefabPath = _buf["prefab_path"]; }
    }

    public static GhostConfig DeserializeGhostConfig(JSONNode _buf)
    {
        return new GhostConfig(_buf);
    }

    public readonly GhostEnum Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    public readonly string PrefabPath;
   
    public const int __ID__ = -301065583;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "prefabPath:" + PrefabPath + ","
        + "}";
    }
}
}

