
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class GhostTable
{
    private readonly System.Collections.Generic.Dictionary<GhostEnum, GhostConfig> _dataMap;
    private readonly System.Collections.Generic.List<GhostConfig> _dataList;
    
    public GhostTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<GhostEnum, GhostConfig>(count);
        _dataList = new System.Collections.Generic.List<GhostConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GhostConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.GhostConfig.DeserializeGhostConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<GhostEnum, GhostConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<GhostConfig> DataList => _dataList;

    public GhostConfig GetOrDefault(GhostEnum key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GhostConfig Get(GhostEnum key) => _dataMap[key];
    public GhostConfig this[GhostEnum key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

