
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum IntentEnum
    {
        攻击 = 0,
        防御 = 1,
        喝咖啡 = 2,
        吸血 = 3,
    }

} 

