
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum MaskEnum
    {
        本我 = 0,
        阎王面具 = 1,
        无常面具 = 2,
        孟婆面具 = 3,
        二郎神面具 = 4,
    }

} 

