
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class MaskTable
{
    private readonly System.Collections.Generic.Dictionary<MaskEnum, MaskConfig> _dataMap;
    private readonly System.Collections.Generic.List<MaskConfig> _dataList;
    
    public MaskTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<MaskEnum, MaskConfig>(count);
        _dataList = new System.Collections.Generic.List<MaskConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MaskConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.MaskConfig.DeserializeMaskConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<MaskEnum, MaskConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<MaskConfig> DataList => _dataList;

    public MaskConfig GetOrDefault(MaskEnum key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public MaskConfig Get(MaskEnum key) => _dataMap[key];
    public MaskConfig this[MaskEnum key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

