
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum MaskEnum
    {
        本我 = 0,
        阎王 = 1,
        十殿阎罗 = 2,
        黑白无常 = 3,
        孟婆 = 4,
        二郎神 = 5,
    }

} 

