
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MaskConfig : Luban.BeanBase
{
    public MaskConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (MaskEnum)_buf["id"].AsInt; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["can_wear_any_time"].IsBoolean) { throw new SerializationException(); }  CanWearAnyTime = _buf["can_wear_any_time"]; }
    }

    public static MaskConfig DeserializeMaskConfig(JSONNode _buf)
    {
        return new MaskConfig(_buf);
    }

    public readonly MaskEnum Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    public readonly bool CanWearAnyTime;
   
    public const int __ID__ = -418680466;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "canWearAnyTime:" + CanWearAnyTime + ","
        + "}";
    }
}
}

