
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MengpoConfig : Luban.BeanBase
{
    public MengpoConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (CardEnum)_buf["id"].AsInt; }
        { var __json0 = _buf["mengpo_soup_effect"]; if(!__json0.IsArray) { throw new SerializationException(); } MengpoSoupEffect = new System.Collections.Generic.Dictionary<CardTypeEnum, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { CardTypeEnum _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = (CardTypeEnum)__e0[0].AsInt; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  MengpoSoupEffect.Add(_k0, _v0); }   }
    }

    public static MengpoConfig DeserializeMengpoConfig(JSONNode _buf)
    {
        return new MengpoConfig(_buf);
    }

    public readonly CardEnum Id;
    public readonly System.Collections.Generic.Dictionary<CardTypeEnum, int> MengpoSoupEffect;
   
    public const int __ID__ = -2000926062;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "mengpoSoupEffect:" + Luban.StringUtil.CollectionToString(MengpoSoupEffect) + ","
        + "}";
    }
}
}

