
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class MengpoTable
{
    private readonly System.Collections.Generic.Dictionary<CardEnum, MengpoConfig> _dataMap;
    private readonly System.Collections.Generic.List<MengpoConfig> _dataList;
    
    public MengpoTable(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<CardEnum, MengpoConfig>(count);
        _dataList = new System.Collections.Generic.List<MengpoConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MengpoConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.MengpoConfig.DeserializeMengpoConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<CardEnum, MengpoConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<MengpoConfig> DataList => _dataList;

    public MengpoConfig GetOrDefault(CardEnum key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public MengpoConfig Get(CardEnum key) => _dataMap[key];
    public MengpoConfig this[CardEnum key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

