
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum PokemonEnum
    {
        隐潮龙 = 0,
        火焰领主 = 1,
        推土牛 = 2,
        侠客螳螂 = 3,
        风绒球 = 4,
        毒宝宝 = 5,
        一口鲸 = 6,
        吞火熊 = 7,
        枯木妖 = 8,
        斯托姆 = 9,
        电电鼠 = 10,
        噼啪小将 = 11,
        小雀儿 = 12,
        布洛克 = 13,
        猛毒蝎 = 14,
        泡泡海豚 = 15,
        火山角羊 = 16,
        刺刺猬 = 17,
        地蟾蜍 = 18,
    }

} 

