
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public CardTable CardTable {get; }
    public GhostTable GhostTable {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        CardTable = new CardTable(loader("cardtable"));
        GhostTable = new GhostTable(loader("ghosttable"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        CardTable.ResolveRef(this);
        GhostTable.ResolveRef(this);
    }
}

}
