using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using FMODUnity;
using UnityEditor;
using UnityEngine;

namespace Framework.Editor
{
    [Serializable]
    public sealed class FMODEditor : AssetPostprocessor
    {
        private const string EventPrefix = "event:/";
        private const string SnapshotPrefix = "snapshot:/";

        private static bool _generating = false;

        private void OnPreprocessAsset()
        {
            // .bytes
            if (assetPath.EndsWith(".bytes") && assetPath.StartsWith("Assets/Resouce/FMODBanks"))
            {
                // 生成事件常量类
                GenerateEventConstClass();
            }
        }


        [Sirenix.OdinInspector.Button("GenerateEventConstClass")]
        private async void GenerateEventConstClass()
        {
            if (_generating)
            {
                return;
            }

            var all = GetAllEventRef();
            _generating = true;
            await GenerateEventConstClassAsync(all);
            _generating = false;
            AssetDatabase.Refresh();
        }


        private Task GenerateEventConstClassAsync(List<EditorEventRef> eventRefs)
        {
            string targetPath = "Assets/Assemblies/GGJ2026/Runtime/FMODName.cs";
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("/*Auto-generated by FMODEditor*/");
            sb.AppendLine("namespace FMOD");
            sb.AppendLine("{");
            sb.AppendLine("    public static class FMODName");
            sb.AppendLine("    {");
            // #region Event
            sb.AppendLine("        public static class Event");
            sb.AppendLine("        {");
            foreach (var eventRef in eventRefs)
            {
                if (!eventRef.Path.StartsWith(EventPrefix))
                {
                    continue;
                }

                sb.AppendLine();
                // 移除前缀
                string eventName = eventRef.Path.Substring(EventPrefix.Length);
                eventName = ProcessString(eventName);
                sb.AppendLine($"        \tpublic const string {eventName} = \"{eventRef.Path}\";");
                if (eventRef.Parameters.Count == 0)
                    continue;

                foreach (var eventRefParameter in eventRef.Parameters)
                {
                    sb.AppendLine($"\t\t\t/// <summary>");
                    sb.AppendLine($"\t\t\t/// {eventRefParameter.Name}");
                    sb.AppendLine($"\t\t\t/// </summary>");

                    string memeberName = ProcessString(eventRefParameter.Name);

                    sb.AppendLine(
                        $"        \tpublic const string {memeberName} = \"{eventRefParameter.Name}\";");
                }
            }

            sb.AppendLine("        }");
            // #endregion
            // #region Snapshot
            sb.AppendLine("        public static class Snapshot");
            sb.AppendLine("        {");
            foreach (var eventRef in eventRefs)
            {
                if (!eventRef.Path.StartsWith(SnapshotPrefix))
                {
                    continue;
                }

                // 移除前缀
                string snapshotName = eventRef.Path.Substring(SnapshotPrefix.Length);
                sb.AppendLine($"        \tpublic const string {snapshotName} = \"{eventRef.Path}\";");
            }

            sb.AppendLine("        }");
            // #endregion
            // #region Bank
            sb.AppendLine("        public static class Bank");
            sb.AppendLine("        {");
            foreach (var editorBankRef in EventManager.Banks)
            {
                string bankName = editorBankRef.Name;
                // 替换. 为_
                bankName = ProcessString(bankName);
                sb.AppendLine($"        \tpublic const string {bankName} = \"{editorBankRef.StudioPath}\";");
            }

            sb.AppendLine("        }");
            // #endregion
            // #region Parameter
            sb.AppendLine("        public static class GlobalParameter");
            sb.AppendLine("        {");
            foreach (var editorParamRef in EventManager.Parameters)
            {
                sb.AppendLine(
                    $"        \tpublic const string {editorParamRef.Name} = \"{editorParamRef.StudioPath}\";");
            }

            sb.AppendLine("        }");
            // #endregion

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return System.IO.File.WriteAllTextAsync(targetPath, sb.ToString());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static string ProcessString(string str)
        {
            // 转utf8
            str = Encoding.UTF8.GetString(Encoding.Default.GetBytes(str));
            // 正则表达式使得其满足C#常量命名规范


            str = ToValidVariableName(str, true);
            return str;
        }


        private static readonly HashSet<string> Keywords = new HashSet<string>
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
            "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw",
            "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
            "virtual", "void", "volatile", "while"
        };

        public static string ToValidVariableName(string input, bool pascalCase = true)
        {
            if (string.IsNullOrWhiteSpace(input)) return "_";

            // 1. 替换非法字符（非字母数字）为空格，方便后续分词
            string cleaned = Regex.Replace(input, @"[^a-zA-Z0-9_]", " ");

            // 2. 按照空格或下划线切分
            string[] words = cleaned.Split(new[] { ' ', '_' }, StringSplitOptions.RemoveEmptyEntries);

            if (words.Length == 0) return "_";

            StringBuilder sb = new StringBuilder();

            for (int i = 0; i < words.Length; i++)
            {
                string word = words[i];
                if (pascalCase || i > 0)
                {
                    // 首字母大写
                    sb.Append(char.ToUpper(word[0]) + word.Substring(1));
                }
                else
                {
                    // 小驼峰首单词全小写
                    sb.Append(char.ToLower(word[0]) + word.Substring(1));
                }
            }

            string result = sb.ToString();

            // 3. 处理首字符是数字的情况
            if (char.IsDigit(result[0]))
            {
                result = "_" + result;
            }

            // 4. 处理关键字冲突
            if (Keywords.Contains(result))
            {
                result = "@" + result;
            }

            return result;
        }

        private List<EditorEventRef> GetAllEventRef()
        {
            List<EditorEventRef> refs = new List<EditorEventRef>();
            var start = EventManager.Events.GetEnumerator();
            var current = start.Current;
            refs.Add(current);
            while (start.MoveNext())
            {
                current = start.Current;
                refs.Add(current);
            }

            refs.RemoveAll(r => r == null);


            return refs;
        }
    }
}